services:
  sd:
    image: proxy-wol
    restart: on-failure
    environment:
      - PORT=7018
      - TARGET_HOST=arch.tt
      - TARGET_PORT=8080
      - TARGET_MAC=7c:10:c9:9e:13:26
      - TARGET_AGENT_PORT=4322
    network_mode: host

  open-webui:
    image: proxy-wol
    restart: on-failure
    environment:
      - PORT=7019
      - TARGET_HOST=arch.tt
      - TARGET_PORT=3000
      - TARGET_MAC=7c:10:c9:9e:13:26
      - TARGET_AGENT_PORT=4322
    network_mode: host
